services:
  - type: web
    name: diia-api
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py flask
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CRYPTOPAY_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
